# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: tendermint/statesync/types.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class Message(betterproto.Message):
    snapshots_request: "SnapshotsRequest" = betterproto.message_field(1, group="sum")
    snapshots_response: "SnapshotsResponse" = betterproto.message_field(2, group="sum")
    chunk_request: "ChunkRequest" = betterproto.message_field(3, group="sum")
    chunk_response: "ChunkResponse" = betterproto.message_field(4, group="sum")
    light_block_request: "LightBlockRequest" = betterproto.message_field(5, group="sum")
    light_block_response: "LightBlockResponse" = betterproto.message_field(
        6, group="sum"
    )
    params_request: "ParamsRequest" = betterproto.message_field(7, group="sum")
    params_response: "ParamsResponse" = betterproto.message_field(8, group="sum")


@dataclass(eq=False, repr=False)
class SnapshotsRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class SnapshotsResponse(betterproto.Message):
    height: int = betterproto.uint64_field(1)
    format: int = betterproto.uint32_field(2)
    chunks: int = betterproto.uint32_field(3)
    hash: bytes = betterproto.bytes_field(4)
    metadata: bytes = betterproto.bytes_field(5)


@dataclass(eq=False, repr=False)
class ChunkRequest(betterproto.Message):
    height: int = betterproto.uint64_field(1)
    format: int = betterproto.uint32_field(2)
    index: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class ChunkResponse(betterproto.Message):
    height: int = betterproto.uint64_field(1)
    format: int = betterproto.uint32_field(2)
    index: int = betterproto.uint32_field(3)
    chunk: bytes = betterproto.bytes_field(4)
    missing: bool = betterproto.bool_field(5)


@dataclass(eq=False, repr=False)
class LightBlockRequest(betterproto.Message):
    height: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class LightBlockResponse(betterproto.Message):
    light_block: "_types__.LightBlock" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ParamsRequest(betterproto.Message):
    height: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class ParamsResponse(betterproto.Message):
    height: int = betterproto.uint64_field(1)
    consensus_params: "_types__.ConsensusParams" = betterproto.message_field(2)


from .. import types as _types__
